# Site settings
title: "Vignesh's Resume"
description: "Vignesh's Resume | CV for Tech Jobs"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: false
resume_name: "C K Vignesh"
resume_title: "Programmer & Writer"

# used for the contact button in _layouts/resume.html
resume_contact_email: "vigneshckprakash@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "+91-871-4440-261"
resume_contact_address: "Kerala"

resume_header_contact_info: "Kerala, India • +91-871-4440-261 • vigneshckprakash@gmail.com"
display_header_contact_info: "true"

resume_header_intro: "<p> Software Engineer who worked with Angular, React and .NET Core to create e-commerce Applications. Skilled in Cloud Computing with AWS and Database Management with SQL Server, Mongo DB. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: true
resume_section_links: true
resume_section_associations: true
resume_section_interests: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/ckvignesh"
  # resume_twitter_url: "http://twitter.com/vigneshCodes"
  # resume_dribbble_url: "https://dribbble.com/"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/ck-vignesh-/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url: "https://ckvignesh.github.io/"
  resume_medium_url: "https://vigneshck.medium.com/"
  resume_hashnode_url: "https://ckvignesh.hashnode.dev/"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts.
